### ISSUE TITLE
PyConv2d

### ISSUE THREAD

**Issue by shuaizzZ** [iduta/pyconv#5]
Why not use PyConv2d module, it seems that using nn.ModuleList will take up more GPU memory?

**Comment by iduta** [comment]
PyConv2d is for the general case, and it looks that nn.ModuleList is the safe way to go for ensuring that the modules it contains are properly registered, otherwise, if using a regular list, it can create problems for the optimizer. This was previously discussed in several posts, for instance [here](https://discuss.pytorch.org/t/when-should-i-use-nn-modulelist-and-when-should-i-use-nn-sequential/5463/17). Alternatively, if you don't want to use nn.ModuleList, you can create directly a custom PyConv2d, for instance, see our PyConv2, PyConv3 or PyConv4 (if needed, for flexibility, you can add there another argument for the number of output feature maps for each level of PyConv).
