### ISSUE TITLE
关于layer层的pyconv核长度递减

### ISSUE THREAD

**Issue by Clarence-wen** [iduta/pyconv#7]
我看您网络的layer层的pyconv的核长度从4递减到1,为什么这么做???可不可以都用长度为4的?

**Comment by iduta** [comment]
I don't actually speak Chinese, but based on Google translate, I understand that you are asking why we decrease the levels of PyConv from 4 to 1 along the network and if you can use 4 levels of PyConv.
As we pointed out in our arXiv (https://arxiv.org/pdf/2006.11538.pdf), we decreased the levels of PyConv throughout the network because the resolution of the feature maps is decreasing along the network, so it is not necessary to have many layers of PyConv (with large receptive fields) when the resolution of the feature maps is quite small. But yes, you can use 4 levels of PyConv throughout the network. This is one strong point of PyConv, that you can search for better combinations of PyConv levels based for instance, on the task that you need to solve or based on the resolution of the feature maps at a given layer.  So, the number of levels of PyConv is not fixed, you can explore different settings of PyConv which can provide better results for a particular task.
